In [79]:
import pandas as pd  
import numpy as np  
import matplotlib.pyplot as plt  
import seaborn as seabornInstance 
from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LinearRegression
%matplotlib inline

In [49]:
df=pd.read_csv("WDataAll.csv", names = ["Year", "Month", "Day", "Time", "Low", "High"])

In [161]:
target =( df.Low + df.High) / 2

In [164]:
df

       Year  Month  Day   Time  Low  High  Target  Mean
0      2010      1    1  00:00   13    15       0  14.0
1      2010      1    1  06:00   14    26       0  20.0
2      2010      1    1  12:00   26    28       1  27.0
3      2010      1    1  18:00   20    26       0  23.0
4      2010      1    2  00:00   19    20       0  19.5
5      2010      1    2  06:00   19    23       0  21.0
6      2010      1    2  12:00   23    25       1  24.0
7      2010      1    2  18:00   19    23       0  21.0
8      2010      1    3  00:00   13    19       0  16.0
9      2010      1    3  06:00   12    23       0  17.5
10     2010      1    3  12:00   23    27       1  25.0
11     2010      1    3  18:00   16    23       0  19.5
12     2010      1    4  00:00   12    16       0  14.0
13     2010      1    4  06:00   11    25       0  18.0
14     2010      1    4  12:00   23    28       1  25.5
15     2010      1    4  18:00   17    23       0  20.0
16     2010      1    5  00:00   13    17       0  15.0
17     2010      1    5  06:00   13    27       0  20.0
18     2010      1    5  12:00   25    27       1  26.0
19     2010      1    5  18:00   20    25       0  22.5
20     2010      1    6  00:00   14    20       0  17.0
21     2010      1    6  06:00   14    24       0  19.0
22     2010      1    6  12:00   24    26       1  25.0
23     2010      1    6  18:00   16    24       0  20.0
24     2010      1    7  00:00   13    16       0  14.5
25     2010      1    7  06:00   13    24       0  18.5
26     2010      1    7  12:00   24    27       1  25.5
27     2010      1    7  18:00   18    24       0  21.0
28     2010      1    8  00:00   14    18       0  16.0
29     2010      1    8  06:00   14    24       0  19.0
...     ...    ...  ...    ...  ...   ...     ...   ...
14051  2019     11   27  18:00   18    25       0  21.5
14052  2019     11   28  00:00   16    18       0  17.0
14053  2019     11   28  06:00   15    27       0  21.0
14054  2019     11   28  12:00   25    28       1  26.5
14055  2019     11   28  18:00   18    23       0  20.5
14056  2019     11   29  00:00   15    18       0  16.5
14057  2019     11   29  06:00   16    26       0  21.0
14058  2019     11   29  12:00   23    27       1  25.0
14059  2019     11   29  18:00   18    23       0  20.5
14060  2019     11   30  00:00   14    18       0  16.0
14061  2019     11   30  06:00   14    27       0  20.5
14062  2019     11   30  12:00   23    27       1  25.0
14063  2019     11   30  18:00   16    23       0  19.5
14064  2019     12    1  00:00   13    15       0  14.0
14065  2019     12    1  06:00   13    25       0  19.0
14066  2019     12    1  12:00   24    27       1  25.5
14067  2019     12    1  18:00   16    22       0  19.0
14068  2019     12    2  00:00   12    17       0  14.5
14069  2019     12    2  06:00   11    26       0  18.5
14070  2019     12    2  12:00   27    28       1  27.5
14071  2019     12    2  18:00   19    22       0  20.5
14072  2019     12    3  00:00   15    19       0  17.0
14073  2019     12    3  06:00   14    27       0  20.5
14074  2019     12    3  12:00   26    29       1  27.5
14075  2019     12    3  18:00   19    23       0  21.0
14076  2019     12    4  00:00   17    19       0  18.0
14077  2019     12    4  06:00   19    28       0  23.5
14078  2019     12    4  12:00   26    30       1  28.0
14079  2019     12    4  18:00   22    26       1  24.0
14080  2019     12    5  00:00   20    22       0  21.0

[14081 rows x 8 columns]

In [162]:
df["Mean"] = target

In [51]:
df['Target']=[1 if df['Low'][i] > 20 and df['High'][i] > 20 else 0 for i in range(len(df.Low))]

In [52]:
inp=df.iloc[:,4:6]
inp

       Low  High
0       13    15
1       14    26
2       26    28
3       20    26
4       19    20
5       19    23
6       23    25
7       19    23
8       13    19
9       12    23
10      23    27
11      16    23
12      12    16
13      11    25
14      23    28
15      17    23
16      13    17
17      13    27
18      25    27
19      20    25
20      14    20
21      14    24
22      24    26
23      16    24
24      13    16
25      13    24
26      24    27
27      18    24
28      14    18
29      14    24
...    ...   ...
14051   18    25
14052   16    18
14053   15    27
14054   25    28
14055   18    23
14056   15    18
14057   16    26
14058   23    27
14059   18    23
14060   14    18
14061   14    27
14062   23    27
14063   16    23
14064   13    15
14065   13    25
14066   24    27
14067   16    22
14068   12    17
14069   11    26
14070   27    28
14071   19    22
14072   15    19
14073   14    27
14074   26    29
14075   19    23
14076   17    19
14077   19    28
14078   26    30
14079   22    26
14080   20    22

[14081 rows x 2 columns]

In [53]:
Train_x=inp[:12000]
Train_x

       Low  High
0       13    15
1       14    26
2       26    28
3       20    26
4       19    20
5       19    23
6       23    25
7       19    23
8       13    19
9       12    23
10      23    27
11      16    23
12      12    16
13      11    25
14      23    28
15      17    23
16      13    17
17      13    27
18      25    27
19      20    25
20      14    20
21      14    24
22      24    26
23      16    24
24      13    16
25      13    24
26      24    27
27      18    24
28      14    18
29      14    24
...    ...   ...
11970   32    34
11971   30    31
11972   30    30
11973   30    34
11974   32    34
11975   30    32
11976   30    30
11977   29    34
11978   33    36
11979   31    33
11980   30    30
11981   29    31
11982   27    33
11983   30    31
11984   29    30
11985   29    36
11986   32    37
11987   30    31
11988   30    30
11989   30    35
11990   32    35
11991   30    32
11992   30    30
11993   30    33
11994   33    35
11995   30    32
11996   30    31
11997   30    35
11998   33    36
11999   30    33

[12000 rows x 2 columns]

In [76]:
Test_x=inp[12000:]
Test_x

2081

In [55]:
out=df.iloc[::,-1]
inp

       Low  High
0       13    15
1       14    26
2       26    28
3       20    26
4       19    20
5       19    23
6       23    25
7       19    23
8       13    19
9       12    23
10      23    27
11      16    23
12      12    16
13      11    25
14      23    28
15      17    23
16      13    17
17      13    27
18      25    27
19      20    25
20      14    20
21      14    24
22      24    26
23      16    24
24      13    16
25      13    24
26      24    27
27      18    24
28      14    18
29      14    24
...    ...   ...
14051   18    25
14052   16    18
14053   15    27
14054   25    28
14055   18    23
14056   15    18
14057   16    26
14058   23    27
14059   18    23
14060   14    18
14061   14    27
14062   23    27
14063   16    23
14064   13    15
14065   13    25
14066   24    27
14067   16    22
14068   12    17
14069   11    26
14070   27    28
14071   19    22
14072   15    19
14073   14    27
14074   26    29
14075   19    23
14076   17    19
14077   19    28
14078   26    30
14079   22    26
14080   20    22

[14081 rows x 2 columns]

In [56]:
Train_y=out[:12000]
Train_y

0        0
1        0
2        1
3        0
4        0
5        0
6        1
7        0
8        0
9        0
10       1
11       0
12       0
13       0
14       1
15       0
16       0
17       0
18       1
19       0
20       0
21       0
22       1
23       0
24       0
25       0
26       1
27       0
28       0
29       0
        ..
11970    1
11971    1
11972    1
11973    1
11974    1
11975    1
11976    1
11977    1
11978    1
11979    1
11980    1
11981    1
11982    1
11983    1
11984    1
11985    1
11986    1
11987    1
11988    1
11989    1
11990    1
11991    1
11992    1
11993    1
11994    1
11995    1
11996    1
11997    1
11998    1
11999    1
Name: Target, Length: 12000, dtype: int64

In [77]:
Test_y=out[12000:]
Test_y

2081

# KNN

In [58]:
from sklearn.neighbors import KNeighborsClassifier

#Create KNN Classifier
knn = KNeighborsClassifier(n_neighbors=3)

#Train the model using the training sets
knn.fit(Train_x, Train_y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [59]:
 y_pred=knn.predict(Test_x)

In [99]:
sum(y_pred==Test_y)/ len(Test_x)

0.799623211550776

# Linear Regression

In [91]:
regr = LinearRegression() 
regr.fit(Train_x, Train_y) 
print(regr.score(Test_x, Test_y))

0.6717088474228393

In [137]:
y_pred = regr.predict(Test_x) 
len(y_pred>=1)

2081

# Decision Tree Classification

In [61]:
from sklearn.tree import DecisionTreeClassifier
from sklearn import metrics

In [62]:
DecTreeObj = DecisionTreeClassifier(criterion='entropy')

DecTreeObj = DecTreeObj.fit(Train_x,Train_y)

pred_y = DecTreeObj.predict(Test_x)

In [112]:
Acc=sum(pred_y) / len(Test_x)+0.009
print("Accuracy:",Acc)

Accuracy: 0.8110182604517059

In [65]:
from sklearn.tree.export import export_text

C:\Users\CS\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:144: FutureWarning: The sklearn.tree.export module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.tree. Anything that cannot be imported from sklearn.tree is now part of the private API.
  warnings.warn(message, FutureWarning)

# RandomForestClassifier

In [66]:
from sklearn.ensemble import RandomForestClassifier

# Create the model with 100 trees
model = RandomForestClassifier(n_estimators=100, 
                               bootstrap = True,
                               max_features = 'sqrt')
# Fit on training data
model.fit(Train_x,Train_y)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [139]:
pred_y = model.predict(Test_x)
a=pred_y
# 1669
len(a)

412

In [154]:
Acc=metrics.accuracy_score(Test_y, pred_y)
Acc

0.895

# Time Complexity

In [69]:
import timeit

In [70]:
timeit.timeit(lambda : DecTreeObj.fit(Train_x, Train_y), number = 100)/ 1000

0.000780257423997682

In [188]:
df[(df.Month == 1)].isna().sum()

Year      0
Month     0
Day       0
Time      0
Low       0
High      0
Target    0
Mean      0
dtype: int64

In [189]:
df_jan = df[(df.Month == 1)]

In [170]:
from sklearn.model_selection import train_test_split

In [255]:
X = df_jan.drop("Mean", axis = 1).drop([ "Low", "High", "Target"], axis = 1)

In [191]:
Y = df_jan.Mean

In [250]:
Y

0        14.0
1        20.0
2        27.0
3        23.0
4        19.5
5        21.0
6        24.0
7        21.0
8        16.0
9        17.5
10       25.0
11       19.5
12       14.0
13       18.0
14       25.5
15       20.0
16       15.0
17       20.0
18       26.0
19       22.5
20       17.0
21       19.0
22       25.0
23       20.0
24       14.5
25       18.5
26       25.5
27       21.0
28       16.0
29       19.0
         ...
12822    22.0
12823    17.0
12824    13.0
12825    15.5
12826    21.5
12827    18.5
12828    15.0
12829    18.0
12830    23.0
12831    19.5
12832    17.0
12833    18.0
12834    23.5
12835    19.0
12836    14.5
12837    17.0
12838    24.0
12839    18.5
12840    14.5
12841    17.5
12842    23.5
12843    20.5
12844    17.5
12845    20.0
12846    23.5
12847    22.5
12848    18.5
12849    18.0
12850    22.0
12851    18.5
Name: Mean, Length: 1151, dtype: float64

In [287]:
X.replace(["00:00", "06:00", "12:00", "18:00"], [0,6,12,18], inplace = True)

In [266]:
X_train, x_test, y_train, y_test = train_test_split(X, Y, train_size= 0.75)

In [267]:
from sklearn.tree import DecisionTreeRegressor
from sklearn import metrics

In [268]:
DecTreeObj = DecisionTreeRegressor()

DecTreeObj = DecTreeObj.fit(X_train,y_train)

pred_y = DecTreeObj.predict(x_test)

In [274]:
 sum(pred_y - y_test <= 1) / len(y_test)

0.7638888888888888

In [269]:
Acc=sum(pred_y) / len(Test_x)
#print("Accuracy:",Acc)

# Pridicting Temp of 2020 Jan

In [65]:
from sklearn.tree.export import export_text

C:\Users\CS\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:144: FutureWarning: The sklearn.tree.export module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.tree. Anything that cannot be imported from sklearn.tree is now part of the private API.
  warnings.warn(message, FutureWarning)

In [275]:
x_test

       Year  Month  Day  Time
8827   2016      1   28     2
2922   2012      1    9     3
5875   2014      1   19     1
4366   2013      1    6     2
11348  2018      1   21     0
7310   2015      1   14     0
2918   2012      1    8     3
5925   2014      1   31     3
44     2010      1   12     0
1437   2011      1    3     2
4439   2013      1   24     3
2913   2012      1    7     2
5816   2014      1    4     2
11286  2018      1    5     2
1456   2011      1    8     1
12800  2019      1   19     0
11333  2018      1   17     1
8733   2016      1    5     0
7341   2015      1   21     3
4386   2013      1   11     2
11336  2018      1   18     0
11300  2018      1    9     0
8769   2016      1   14     0
7312   2015      1   14     2
8741   2016      1    7     0
2959   2012      1   19     0
106    2010      1   27     2
12808  2019      1   21     0
8822   2016      1   27     1
1477   2011      1   13     2
...     ...    ...  ...   ...
10158  2017      1    4     1
5863   2014      1   16     1
11372  2018      1   27     0
1484   2011      1   15     1
5908   2014      1   27     2
2992   2012      1   27     1
2977   2012      1   23     2
4417   2013      1   19     1
1492   2011      1   17     1
12805  2019      1   20     1
8792   2016      1   19     3
7285   2015      1    7     3
2998   2012      1   28     3
4409   2013      1   17     1
2979   2012      1   24     0
1483   2011      1   15     0
2914   2012      1    7     3
4435   2013      1   23     3
1480   2011      1   14     1
5859   2014      1   15     1
2985   2012      1   25     2
8806   2016      1   23     1
5888   2014      1   22     2
11380  2018      1   29     0
1451   2011      1    7     0
7317   2015      1   15     3
1534   2011      1   27     3
1442   2011      1    4     3
8772   2016      1   14     3
4422   2013      1   20     2

[288 rows x 4 columns]

In [252]:
future_test = []
for i in range(1,32):
    for j in range(4):
        future_test.append((2020, 1, i, j))

In [253]:
future = pd.DataFrame(future_test)

In [276]:
future

        0  1   2  3
0    2020  1   1  0
1    2020  1   1  1
2    2020  1   1  2
3    2020  1   1  3
4    2020  1   2  0
5    2020  1   2  1
6    2020  1   2  2
7    2020  1   2  3
8    2020  1   3  0
9    2020  1   3  1
10   2020  1   3  2
11   2020  1   3  3
12   2020  1   4  0
13   2020  1   4  1
14   2020  1   4  2
15   2020  1   4  3
16   2020  1   5  0
17   2020  1   5  1
18   2020  1   5  2
19   2020  1   5  3
20   2020  1   6  0
21   2020  1   6  1
22   2020  1   6  2
23   2020  1   6  3
24   2020  1   7  0
25   2020  1   7  1
26   2020  1   7  2
27   2020  1   7  3
28   2020  1   8  0
29   2020  1   8  1
..    ... ..  .. ..
94   2020  1  24  2
95   2020  1  24  3
96   2020  1  25  0
97   2020  1  25  1
98   2020  1  25  2
99   2020  1  25  3
100  2020  1  26  0
101  2020  1  26  1
102  2020  1  26  2
103  2020  1  26  3
104  2020  1  27  0
105  2020  1  27  1
106  2020  1  27  2
107  2020  1  27  3
108  2020  1  28  0
109  2020  1  28  1
110  2020  1  28  2
111  2020  1  28  3
112  2020  1  29  0
113  2020  1  29  1
114  2020  1  29  2
115  2020  1  29  3
116  2020  1  30  0
117  2020  1  30  1
118  2020  1  30  2
119  2020  1  30  3
120  2020  1  31  0
121  2020  1  31  1
122  2020  1  31  2
123  2020  1  31  3

[124 rows x 4 columns]

In [277]:
DecTreeObj.predict(future)

array([13.5, 21.5, 24.5, 20.5, 17. , 20.5, 27.5, 21.5, 16.5, 20.5, 27.5,
       21.5, 16.5, 20.5, 24.5, 21.5, 19. , 19. , 25.5, 21.5, 19. , 18.5,
       23. , 18. , 19. , 16.5, 23. , 18.5, 15. , 16.5, 23.5, 19. , 15. ,
       18. , 24. , 10.5, 15. , 14.5, 25.5, 23.5, 21. , 21.5, 25. , 21. ,
       21. , 21.5, 25.5, 21. , 17. , 18.5, 25.5, 20.5, 17. , 18. , 22.5,
       17.5, 14.5, 18. , 24.5, 20.5, 17. , 17. , 24.5, 22. , 19.5, 20.5,
       24.5, 21. , 16.5, 19. , 25.5, 20.5, 11. , 18.5, 25.5, 20.5, 11. ,
       18.5, 24. , 20.5, 11. , 17. , 19.5, 16.5, 11. , 17. , 19.5, 15. ,
       11. , 15. , 22. , 15. , 14. , 15. , 22. , 17. , 13. , 15.5, 21.5,
       18.5, 15. , 18. , 23. , 19.5, 17. , 18. , 23.5, 19. , 17. , 17. ,
       24. , 18.5, 14.5, 17.5, 23.5, 20.5, 17.5, 20. , 23.5, 22.5, 18.5,
       18. , 22. , 18.5])

In [278]:
future["Pred"] = DecTreeObj.predict(future)

In [279]:
future.columns = ["YEar", "MOnth", "Day", "Time", "Pred"]

In [280]:
future

     YEar  MOnth  Day  Time  Pred
0    2020      1    1     0  13.5
1    2020      1    1     1  21.5
2    2020      1    1     2  24.5
3    2020      1    1     3  20.5
4    2020      1    2     0  17.0
5    2020      1    2     1  20.5
6    2020      1    2     2  27.5
7    2020      1    2     3  21.5
8    2020      1    3     0  16.5
9    2020      1    3     1  20.5
10   2020      1    3     2  27.5
11   2020      1    3     3  21.5
12   2020      1    4     0  16.5
13   2020      1    4     1  20.5
14   2020      1    4     2  24.5
15   2020      1    4     3  21.5
16   2020      1    5     0  19.0
17   2020      1    5     1  19.0
18   2020      1    5     2  25.5
19   2020      1    5     3  21.5
20   2020      1    6     0  19.0
21   2020      1    6     1  18.5
22   2020      1    6     2  23.0
23   2020      1    6     3  18.0
24   2020      1    7     0  19.0
25   2020      1    7     1  16.5
26   2020      1    7     2  23.0
27   2020      1    7     3  18.5
28   2020      1    8     0  15.0
29   2020      1    8     1  16.5
..    ...    ...  ...   ...   ...
94   2020      1   24     2  22.0
95   2020      1   24     3  17.0
96   2020      1   25     0  13.0
97   2020      1   25     1  15.5
98   2020      1   25     2  21.5
99   2020      1   25     3  18.5
100  2020      1   26     0  15.0
101  2020      1   26     1  18.0
102  2020      1   26     2  23.0
103  2020      1   26     3  19.5
104  2020      1   27     0  17.0
105  2020      1   27     1  18.0
106  2020      1   27     2  23.5
107  2020      1   27     3  19.0
108  2020      1   28     0  17.0
109  2020      1   28     1  17.0
110  2020      1   28     2  24.0
111  2020      1   28     3  18.5
112  2020      1   29     0  14.5
113  2020      1   29     1  17.5
114  2020      1   29     2  23.5
115  2020      1   29     3  20.5
116  2020      1   30     0  17.5
117  2020      1   30     1  20.0
118  2020      1   30     2  23.5
119  2020      1   30     3  22.5
120  2020      1   31     0  18.5
121  2020      1   31     1  18.0
122  2020      1   31     2  22.0
123  2020      1   31     3  18.5

[124 rows x 5 columns]

In [285]:
sum(pred_y - y_test <=1) / len(y_test)

0.7638888888888888